// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
  NEXT_CACHE_WORKERS_KV: KVNamespace
  BUCKET_POI_DB: R2Bucket
  BUCKET_POI_NIGHTLIES: R2Bucket
  ASSETS: Fetcher
}
